FROM node:13.8.0-alpine As builderapp
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build

FROM nginx:1.19-alpine
COPY --from=builderapp /app/dist/bigBoard/ /usr/share/nginx/html